services:
  fastapi:
    build: ..
    command: uvicorn --factory app.main:create_app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ..:/code
    ports:
      - "8000:8000"
    networks:
      - nextcalc_network
    container_name: nc-fastapi

networks:
  nextcalc_network:
    driver: bridge
